apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-career-day-biel-2016
  labels:
    name: hello-career-day-biel-2016
spec:
  replicas: 2
  selector:
    name: hello-career-day-biel-2016
  template:
    metadata:
      labels:
        name: hello-career-day-biel-2016
    spec:
      containers:
        - image: sontags/hello-career-day-biel-2016
          name: hello-career-day-biel-2016
          ports:
          - containerPort: 80
