apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-world
  labels:
    name: hello-world
spec:
  replicas: 2
  selector:
    name: hello-world
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
        - image: tutum/hello-world
          name: hello-world
          ports:
          - containerPort: 80
