---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: generate ssh.config for using jumphost access
    template: src=files/jumphost_sshconfig/ssh.config.j2 dest=./ssh.config
